# these are defaults for RCM new sessions json is

logging:
  RCM.composer: warning
  RCM.baseconfig: warning
  RCM.platformconfig: warning
  RCM.rcm_protocol_parser: warning



schema:

  substitutions :
    SCHEDULER: "NO SCHEDULER DEFINED"
    SCHEDULER.HEADER: ""
    SERVICE: "NO SERVICE DEFINED"
    SERVICE_START: ""
    SCRIPT: |
      #!/bin/bash
      # Using scheduler @{SCHEDULER}
      @{SCHEDULER.HEADER}
      # Service:  @{SERVICE}
      @{SERVICE.START}

  SCHEDULER:
    label : 'Scheduler'
    type : 'combobox'
    children :

  DIVIDER:
    type: 'divider'
    values:
      style: "hline"

  SERVICE :
    label : 'Service Type'
    type: 'combobox'
    children :
