# these are defaults for RCM new sessions json is

logging:
  RCM.composer: warning
  RCM.baseconfig: warning
  RCM.platformconfig: warning
  RCM.rcm_protocol_parser: warning



schema:

  substitutions :
    SCRIPT: |
      #!/bin/bash
      # Using scheduler @{SCHEDULER}
      @{SCHEDULER_HEADER}
      # Starting service @{SERVICE}
      @{SERVICE_START}

  SCHEDULER:
    label : 'Scheduler'
    type : 'combobox'
    list :
      substitutions :
        SCHEDULER_HEADER : ""
      ACCOUNT :
        label : 'Account'
        type : 'combobox'

  #composites
      QUEUE :
        label : 'Queue'
        type : 'combobox'
        list :
          MEMORY :
            label : 'Memory'
            type : 'slider'
            values :
              min : 1
              max : 120
          CPU :
            label : 'CPU'
            type : 'slider'
            values :
              min : 1
              max : 36
          TIME :
            label : 'Time (sec)'
            type : 'slider'
            values :
              min : 1
              max : 360000

  DIVIDER:
    type: 'divider'
    values:
      style: "hline"

  SERVICE :
    label : 'Service Type'
    type: 'combobox'
    list :
      substitutions :
        SERVICE_START : |
          # Running command
          @{COMMAND}


      DIVIDER:
        type: 'divider'
        values:
          style: "hline"
      COMMAND :
        label : 'Command'
        type : 'combobox'
        list :
          WM :
            label : 'Window Manager'
            type : 'combobox'
            list:
              substitutions :
                WM: ""
                WM_FLAGS: ""

          DISPLAY :
            label : 'Display size'
            type : 'combobox'