schema:

  SERVICE :
    label : 'Service Type'
    type: 'combobox'
    children :
      substitutions :
        COMMAND_LINE: ""
        START : |
          # Running service app @{COMMAND}
          @{COMMAND_LINE}


      DIVIDER:
        type: 'divider'
        values:
          style: "hline"
      COMMAND :
        label : 'Command'
        type : 'combobox'
        children :
          substitutions :
#            COMMAND: "vncserver @{WM_FLAGS} $vnc_foreground -geometry @{DISPLAY} -rfbauth $RCM_JOBLOG.pwd  @{WM_COMMAND "

          WM :
            label : 'Window Manager'
            type : 'combobox'
            children:
              substitutions :
                WM_COMMAND: ""
                WM_FLAGS: ""

          DISPLAY :
            label : 'Display size'
            type : 'combobox'
