# these are defaults for RCM new sessions json is

logging:
  RCM.composer: warning
  RCM.baseconfig: warning
  RCM.platformconfig: warning
  RCM.rcm_protocol_parser: warning



schema:

  TOP:
    substitutions :
      SCHEDULER: "NO SCHEDULER DEFINED"
      SCHEDULER.HEADER: ""
      SCHEDULER.FOOTER: ""
      SCHEDULER.BACKGROUND: ""
      SERVICE: "NO SERVICE DEFINED"
      SERVICE.REDIRECT: ""
      SCRIPT: |
        #!/bin/bash
        # Using scheduler @{SCHEDULER}
        @{SCHEDULER.HEADER}
        # Service:  @{SERVICE}
        @{SERVICE.COMMAND.COMMAND_LINE} @{SERVICE.REDIRECT} @{SCHEDULER.BACKGROUND}
        @{SCHEDULER.FOOTER}

    children:
      SCHEDULER:
        label : 'Scheduler'
        type : 'combobox'
        children :

      DIVIDER:
        type: 'divider'
        values:
          style: "hline"

      SERVICE :
        label : 'Service Type'
        type: 'combobox'
        substitutions :

          COMMAND.LOGFILE: "@{RCM_SESSION_FOLDER}/service.log"
          REDIRECT: " > @{RCM_SESSION_FOLDER}/@{COMMAND.LOGFILE} 2>&1 "

        children :
