# This is a basic workflow to help you get started with Actions

name: RCM_CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev", "feature/*" ]
    tags:
      - v*
  pull_request:
    branches: [ "dev", "feature/*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  RCM_CHECKOUT: "."
  PYTHON_VERSION: "3.10.11"
  PYENV_VERSION: "2.3.35"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        os:
        - windows-latest
        - ubuntu-latest	
        - ubuntu-20.04
        turbovnc-version:
        - '3.1'
        - '2.2.7'
        include:
          - os: macos-latest
            turbovnc-version: 'none'

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install Qt missing libraries (linux only)
        uses: awalsh128/cache-apt-pkgs-action@latest
        if: ${{ contains(matrix.os, 'ubuntu')  }}
        with:
          packages: qtbase5-dev qt5-qmake qtwayland5
          version: 1.0-${{ matrix.os }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout RCM
        uses: actions/checkout@v4.1.1

      # CACHE
      - name: (GHO) Cache pyenv
        uses: actions/cache@v4.0.0
        id: cache-pyenv
        with:
          path: .pyenv
          key: pyenv-${{ env.PYENV_VERSION }}-python-${{ env.PYTHON_VERSION }}-${{ matrix.os }}

      # PYTHON
      - name: Setup pyenv environment
        uses: carlkidcrypto/os-specific-runner@v2.0.0
        with:
          macos: . "${RCM_CHECKOUT}/scripts/ci/01-setup-pyenv.sh"
          linux: . "${RCM_CHECKOUT}/scripts/ci/01-setup-pyenv.sh"
          windows: . "${env:RCM_CHECKOUT}\scripts\ci\01-setup-pyenv.ps1"

      - name: Install pyenv locally
        if: ${{steps.cache-pyenv.outputs.cache-hit != 'true' }}
        uses: carlkidcrypto/os-specific-runner@v2.0.0
        with:
          macos: . "${RCM_CHECKOUT}/scripts/ci/02-install-python.sh"
          linux: . "${RCM_CHECKOUT}/scripts/ci/02-install-python.sh"
          windows: . "${env:RCM_CHECKOUT}\scripts\ci\02-install-python.ps1"

      # - name: (GHO) Cache venv
      #   uses: actions/cache@v4.0.0
      #   id: cache-venv
      #   with:
      #     path: .venv
      #     key: venv-${{ hashFiles( format('{0}/pyproject.toml', env.RCM_CHECKOUT )) }}${{ hashFiles( format('{0}/scripts/external_hook.py', env.RCM_CHECKOUT )) }}-turbovnc-${{ matrix.turbovnc-version }}-${{ matrix.os }}
      # if: ${{steps.cache-pyenv.outputs.cache-hit != 'true' }}

      - name: Install venv and RCM-client
        uses: carlkidcrypto/os-specific-runner@v2.0.0
        with:
          macos: |
            python -m venv "${RCM_CHECKOUT:?}/.venv"
            source "${RCM_CHECKOUT:?}/.venv/bin/activate"
            export RCM_INSTALL_EXTERNAL=true
            export TURBOVNC_VERSION=${{ matrix.turbovnc-version }}
            pip install "${RCM_CHECKOUT:?}[dev]"
          linux: |
            python -m venv "${RCM_CHECKOUT:?}/.venv"
            source "${RCM_CHECKOUT:?}/.venv/bin/activate"
            export RCM_INSTALL_EXTERNAL=true
            export TURBOVNC_VERSION=${{ matrix.turbovnc-version }}
            pip install "${RCM_CHECKOUT:?}[dev]"
          windows: |
            python.exe -m venv "${env:RCM_CHECKOUT}/.venv"
            . "${env:RCM_CHECKOUT}\.venv\Scripts\Activate.ps1"
            $env:RCM_INSTALL_EXTERNAL = "true"
            $env:TURBOVNC_VERSION = ${{ matrix.turbovnc-version }}
            pip install "${env:RCM_CHECKOUT}[dev]"

      # PYINSTALLER
      - name: Build pyinstaller
        uses: carlkidcrypto/os-specific-runner@v2.0.0
        with:
          macos: |
            source .venv/bin/activate
            pyinstaller "${RCM_CHECKOUT}/rcm/client/rcm_client_qt.spec"
          linux: |
            source .venv/bin/activate
            pyinstaller "${RCM_CHECKOUT}/rcm/client/rcm_client_qt.spec"
          windows: |
            .venv\Scripts\Activate.ps1
            pyinstaller "${env:RCM_CHECKOUT}\rcm\client\rcm_client_qt.spec"
  
      # ARTIFACT
      - name: (GHO) Define EXT
        uses: carlkidcrypto/os-specific-runner@v2.0.0
        with:
          macos: echo "EXT=" >> "${GITHUB_ENV}"
          linux: echo "EXT=" >> "${GITHUB_ENV}"
          windows: echo "EXT=.exe" >> "${env:GITHUB_ENV}"

      - name: (GHO) Move preartifacts
        shell: bash
        run: |
          # https://github.com/actions/upload-artifact?tab=readme-ov-file#permission-loss
          mv rcm rcm_bck
          find dist -type f -name "RCM${EXT}" -exec cp '{}' . \;
          find dist -type f -name "RCM.zip" -exec cp '{}' . \;

      - name: (GHO) Install cosign
        uses: sigstore/cosign-installer@v3.3.0

      - name: (GHO) Sign image with a key
        shell: bash
        run: |
          cosign sign-blob --yes --key env://COSIGN_PRIVATE_KEY --bundle "RCM.bundlesig" "RCM${EXT}"
          cosign sign-blob --yes --key env://COSIGN_PRIVATE_KEY --bundle "RCM-zip.bundlesig" "RCM.zip"
          cosign verify-blob --bundle "RCM.bundlesig" "RCM${EXT}"
          cosign verify-blob --bundle "RCM-zip.bundlesig" "RCM.zip"
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

      - name: (GHO)(TAG) Upload exe to release
        if: ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/') }}  
        uses: svenstaro/upload-release-action@v2
        with:
          file: RCM${{ env.EXT }}
          asset_name: RCM-client_${{ matrix.os }}_turbovnc_${{ matrix.turbovnc-version }}${{ env.EXT }}
          prerelease: true
          overwrite: true
          tag: ${{ github.ref }}
  
      - name: (GHO)(TAG) Upload sign to release
        if: ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/') }}  
        uses: svenstaro/upload-release-action@v2
        with:
          file: RCM.bundlesig
          asset_name: RCM-client_${{ matrix.os }}_turbovnc_${{ matrix.turbovnc-version }}.bundlesig
          prerelease: true
          overwrite: true
          tag: ${{ github.ref }}

      - name: (GHO) Upload exe
        if: ${{ github.event_name != 'push' && !contains(github.ref, 'refs/tags/') }}  
        uses: actions/upload-artifact@v4.3.1
        with:
          name: RCM-client-${{ matrix.os }}-turbovnc-${{ matrix.turbovnc-version }}
          path: |
            RCM${{ env.EXT }}
            RCM.bundlesig
            RCM.pub

      - name: (GHO) Upload dir
        if: ${{ github.event_name != 'push' && !contains(github.ref, 'refs/tags/') }} 
        uses: actions/upload-artifact@v4.3.1
        with:
          name: RCM-client-${{ matrix.os }}-turbovnc-${{ matrix.turbovnc-version }}-dir
          path: |
            RCM.zip
            RCM-zip.bundlesig
            RCM.pub

      - name: (GHO) Restore RCM-repo
        shell: bash
        run: |
          rm -rf RCM RCM.exe RCM-dir
          mv rcm_bck rcm


  nightly-link:
    runs-on: ubuntu-latest
    if: ${{ always() }} && ${{ github.event_name != 'push' && !contains(github.ref, 'refs/tags/') }}  
    steps:
      - name: Generate Annotation
        run: |
          url="https://nightly.link/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "::notice title=Download the artificats from nightly.link (without logging in) by visiting the URL below::$url"
